### ISSUE TITLE
Catppuccin and dracula

### ISSUE THREAD

**Issue by pewduckwei** [sainnhe/capitaine-cursors#1]
Can you add two color variants with the catppuccin and dracula scheme?

**Comment by sainnhe** [comment]
Nope.

Cursor themes are unlike editor themes, palettes with similar colors will be indistinguishable.

For example, the editor themes made with the Nord palette and the Palenight palette are very different, but the cursor themes they make are very similar, even somewhat indistinguishable.

Similarly, the Catppuccin palette and Dracula palette are very similar to Palenight palette, so the cursor theme they made will be almost the same as Palenight.

Btw, I plan to create some new variants with more distinctive palettes.
