### ISSUE TITLE
The default cursor theme is ths same as gruvbox theme?

### ISSUE THREAD

**Issue by wangxa** [sainnhe/capitaine-cursors#2]
I tried to build the default dark and gruvbox dark themes by:

```bash
$ ./build.sh -d hd -t dark -p unix -s Gruvbox
```
and 

```bash
$ ./build.sh -d hd -t dark -p unix -s Default
```

But the results seem to be the same as the gruvbox theme, if I use `gnome-tweaks` to set up cursor theme.

**Comment by sainnhe** [comment]
Maybe I should add this step to build.sh

**Comment by wangxa** [comment]
Thank you. I see.
