### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by Yushi5058** [sainnhe/capitaine-cursors#5]
Hello,
I was trying to install the AUR package with paru more than two times and it seems that it throws an error so I tried by building it from source and I got an error too 
Here are the errors output : 
![2024-06-30_22-04-25](https://github.com/sainnhe/capitaine-cursors/assets/108335997/3e12b876-91e3-4db6-9f28-b0a8a00fb8ec)
Thank you

**Comment by sainnhe** [comment]
I'm not using arch linux now and that package has been orphanized. Welcome to take over it if you like.
